// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514152916_update_integration_connection")]
    partial class update_integration_connection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("API.Models.CampaignActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("activity_type");

                    b.Property<Guid>("CampaignContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.HasKey("Id")
                        .HasName("pk_campaign_activities");

                    b.HasIndex("CampaignContactId")
                        .HasDatabaseName("ix_campaign_activities_campaign_contact_id");

                    b.ToTable("campaign_activities", (string)null);
                });

            modelBuilder.Entity("API.Models.CampaignActivityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_activity_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_campaign_activity_events");

                    b.HasIndex("CampaignActivityId")
                        .HasDatabaseName("ix_campaign_activity_events_campaign_activity_id");

                    b.ToTable("campaign_activity_events", (string)null);
                });

            modelBuilder.Entity("API.Models.CampaignContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.HasKey("Id")
                        .HasName("pk_campaign_contacts");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_campaign_contacts_contact_id");

                    b.HasIndex("CampaignId", "ContactId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_contacts_campaign_id_contact_id");

                    b.ToTable("campaign_contacts", (string)null);
                });

            modelBuilder.Entity("API.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("Address2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address2");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<bool>("Collections")
                        .HasColumnType("boolean")
                        .HasColumnName("collections");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<bool?>("CompanySpecialBilling")
                        .HasColumnType("boolean")
                        .HasColumnName("company_special_billing");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<long?>("HubspotCompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("hubspot_company_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsNewCompany")
                        .HasColumnType("boolean")
                        .HasColumnName("is_new_company");

                    b.Property<DateTimeOffset?>("LastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<string>("LegacyPrimaryCategory")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legacy_primary_category");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("PrimaryRepName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("primary_rep_name");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<string>("TaxId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tax_id");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.Property<bool>("WriteOff")
                        .HasColumnType("boolean")
                        .HasColumnName("write_off");

                    b.Property<string>("Zip")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("API.Models.CompanyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_company_contact");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_company_contact_company_id");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_company_contact_contact_id");

                    b.HasIndex("CompanyId", "ContactId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_contact_company_id_contact_id");

                    b.HasIndex("CompanyId", "IsPrimary")
                        .HasDatabaseName("ix_company_contact_company_id_is_primary");

                    b.ToTable("company_contact", (string)null);
                });

            modelBuilder.Entity("API.Models.CompanyContactEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_contact_id");

                    b.Property<bool>("DoNotEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("do_not_email");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.HasKey("Id")
                        .HasName("pk_company_contact_email");

                    b.HasIndex("CompanyContactId")
                        .HasDatabaseName("ix_company_contact_email_company_contact_id");

                    b.HasIndex("Email", "CompanyContactId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_contact_email_email_company_contact_id");

                    b.ToTable("company_contact_email", (string)null);
                });

            modelBuilder.Entity("API.Models.CompanyContactPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_contact_id");

                    b.Property<bool>("DoNotCall")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("do_not_call");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_company_contact_phone");

                    b.HasIndex("CompanyContactId")
                        .HasDatabaseName("ix_company_contact_phone_company_contact_id");

                    b.HasIndex("Phone", "CompanyContactId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_contact_phone_phone_company_contact_id");

                    b.ToTable("company_contact_phone", (string)null);
                });

            modelBuilder.Entity("API.Models.CompanyContactRole", b =>
                {
                    b.Property<Guid>("CompanyContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_contact_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("CompanyContactId", "RoleId")
                        .HasName("pk_company_contact_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_company_contact_role_role_id");

                    b.ToTable("company_contact_role", (string)null);
                });

            modelBuilder.Entity("API.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Department")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("department");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gender");

                    b.Property<string>("HubspotId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hubspot_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("job_title");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_date");

                    b.Property<string>("LeadSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lead_source");

                    b.Property<string>("LeadStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lead_status");

                    b.Property<string>("Salutation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("salutation");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<string>("UserRepId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_rep_id");

                    b.Property<string>("Zip")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_contact");

                    b.HasIndex("FirstName")
                        .HasDatabaseName("ix_contact_first_name");

                    b.HasIndex("HubspotId")
                        .HasDatabaseName("ix_contact_hubspot_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_contact_is_active");

                    b.HasIndex("LastName")
                        .HasDatabaseName("ix_contact_last_name");

                    b.HasIndex("UserRepId")
                        .HasDatabaseName("ix_contact_user_rep_id");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("ix_contact_first_name_last_name");

                    b.HasIndex("LastName", "FirstName", "City")
                        .HasDatabaseName("ix_contact_last_name_first_name_city");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("API.Models.ContactEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<bool>("DoNotEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("do_not_email");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.HasKey("Id")
                        .HasName("pk_contact_email");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_contact_email_contact_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_contact_email_email");

                    b.ToTable("contact_email", (string)null);
                });

            modelBuilder.Entity("API.Models.EmailEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmailMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("email_message_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_event_id");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Id")
                        .HasName("pk_email_event");

                    b.HasIndex("EmailMessageId")
                        .HasDatabaseName("ix_email_event_email_message_id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_email_event_event_type");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_email_event_occurred_at");

                    b.HasIndex("ProviderEventId")
                        .HasDatabaseName("ix_email_event_provider_event_id");

                    b.ToTable("email_event", (string)null);
                });

            modelBuilder.Entity("API.Models.EmailLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmailMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("email_message_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_url");

                    b.HasKey("Id")
                        .HasName("pk_email_link");

                    b.HasIndex("EmailMessageId")
                        .HasDatabaseName("ix_email_link_email_message_id");

                    b.ToTable("email_link", (string)null);
                });

            modelBuilder.Entity("API.Models.EmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_html");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid?>("CompanyContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_contact_id");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid?>("MailMergeTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("mail_merge_template_id");

                    b.Property<string>("PlainText")
                        .HasColumnType("text")
                        .HasColumnName("plain_text");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text")
                        .HasColumnName("provider_message_id");

                    b.Property<DateTimeOffset?>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("ToDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("to_display_name");

                    b.Property<string>("ToEmailAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_email_address");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_email_message");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_email_message_campaign_id");

                    b.HasIndex("CompanyContactId")
                        .HasDatabaseName("ix_email_message_company_contact_id");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_email_message_contact_id");

                    b.HasIndex("MailMergeTemplateId")
                        .HasDatabaseName("ix_email_message_mail_merge_template_id");

                    b.HasIndex("ProviderMessageId")
                        .HasDatabaseName("ix_email_message_provider_message_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_email_message_status");

                    b.ToTable("email_message", (string)null);
                });

            modelBuilder.Entity("API.Models.ExternalIdMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("InternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("internal_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_table");

                    b.HasKey("Id")
                        .HasName("pk_external_id_map");

                    b.HasIndex("SourceSystem", "SourceTable", "SourceId", "EntityType")
                        .IsUnique()
                        .HasDatabaseName("ix_external_id_map_source_system_source_table_source_id_entity");

                    b.ToTable("external_id_map", (string)null);
                });

            modelBuilder.Entity("API.Models.ExternalRecordLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_entity_type");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<Guid>("IntegrationConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_connection_id");

                    b.Property<Guid>("InternalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("internal_entity_id");

                    b.Property<string>("InternalEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("internal_entity_type");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_sync_error");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("ProviderMetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("provider_metadata_json");

                    b.Property<string>("SyncStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sync_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_external_record_link");

                    b.HasIndex("IntegrationConnectionId", "ExternalEntityType", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_external_record_link_integration_connection_id_external_ent");

                    b.HasIndex("IntegrationConnectionId", "InternalEntityType", "InternalEntityId", "ExternalEntityType")
                        .IsUnique()
                        .HasDatabaseName("ix_external_record_link_integration_connection_id_internal_ent");

                    b.ToTable("external_record_link", (string)null);
                });

            modelBuilder.Entity("API.Models.IntegrationConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("auth_type");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_integration_connection");

                    b.HasIndex("Provider", "DisplayName")
                        .IsUnique()
                        .HasDatabaseName("ix_integration_connection_provider_display_name");

                    b.ToTable("integration_connection", (string)null);
                });

            modelBuilder.Entity("API.Models.IntegrationSyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("direction");

                    b.Property<Guid?>("ExternalRecordLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_record_link_id");

                    b.Property<Guid>("IntegrationConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_connection_id");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_integration_sync_log");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_integration_sync_log_created_at");

                    b.HasIndex("ExternalRecordLinkId")
                        .HasDatabaseName("ix_integration_sync_log_external_record_link_id");

                    b.HasIndex("IntegrationConnectionId")
                        .HasDatabaseName("ix_integration_sync_log_integration_connection_id");

                    b.ToTable("integration_sync_log", (string)null);
                });

            modelBuilder.Entity("API.Models.MailMergeTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyHtml")
                        .HasColumnType("text")
                        .HasColumnName("body_html");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PlainText")
                        .HasColumnType("text")
                        .HasColumnName("plain_text");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_template");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_mail_merge_template");

                    b.ToTable("mail_merge_template", (string)null);
                });

            modelBuilder.Entity("API.Models.MailMergeTemplateField", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("MergeFieldKey")
                        .HasColumnType("text")
                        .HasColumnName("merge_field_key");

                    b.HasKey("TemplateId", "MergeFieldKey")
                        .HasName("pk_mail_merge_template_field");

                    b.HasIndex("MergeFieldKey")
                        .HasDatabaseName("ix_mail_merge_template_field_merge_field_key");

                    b.ToTable("mail_merge_template_field", (string)null);
                });

            modelBuilder.Entity("API.Models.MergeField", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_type");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.HasKey("Key")
                        .HasName("pk_merge_field");

                    b.ToTable("merge_field", (string)null);
                });

            modelBuilder.Entity("API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_role_name");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsSystem = true,
                            Name = "Billing"
                        },
                        new
                        {
                            Id = 2,
                            IsSystem = true,
                            Name = "Print Artwork"
                        },
                        new
                        {
                            Id = 3,
                            IsSystem = true,
                            Name = "Digital Artwork"
                        },
                        new
                        {
                            Id = 4,
                            IsSystem = true,
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("API.Models.CampaignActivity", b =>
                {
                    b.HasOne("API.Models.CampaignContact", "CampaignContact")
                        .WithMany("Activities")
                        .HasForeignKey("CampaignContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_activities_campaign_contacts_campaign_contact_id");

                    b.Navigation("CampaignContact");
                });

            modelBuilder.Entity("API.Models.CampaignActivityEvent", b =>
                {
                    b.HasOne("API.Models.CampaignActivity", "CampaignActivity")
                        .WithMany("Events")
                        .HasForeignKey("CampaignActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_activity_events_campaign_activities_campaign_activ");

                    b.Navigation("CampaignActivity");
                });

            modelBuilder.Entity("API.Models.CampaignContact", b =>
                {
                    b.HasOne("API.Models.Campaign", "Campaign")
                        .WithMany("CampaignContacts")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_contacts_campaigns_campaign_id");

                    b.HasOne("API.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_contacts_contacts_contact_id");

                    b.Navigation("Campaign");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("API.Models.CompanyContact", b =>
                {
                    b.HasOne("API.Models.Company", "Company")
                        .WithMany("CompanyContacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_contact_company_company_id");

                    b.HasOne("API.Models.Contact", "Contact")
                        .WithMany("CompanyContacts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_contact_contact_contact_id");

                    b.Navigation("Company");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("API.Models.CompanyContactEmail", b =>
                {
                    b.HasOne("API.Models.CompanyContact", "CompanyContact")
                        .WithMany("Emails")
                        .HasForeignKey("CompanyContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_contact_email_company_contact_company_contact_id");

                    b.Navigation("CompanyContact");
                });

            modelBuilder.Entity("API.Models.CompanyContactPhone", b =>
                {
                    b.HasOne("API.Models.CompanyContact", "CompanyContact")
                        .WithMany("Phones")
                        .HasForeignKey("CompanyContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_contact_phone_company_contact_company_contact_id");

                    b.Navigation("CompanyContact");
                });

            modelBuilder.Entity("API.Models.CompanyContactRole", b =>
                {
                    b.HasOne("API.Models.CompanyContact", "CompanyContact")
                        .WithMany("Roles")
                        .HasForeignKey("CompanyContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_contact_role_company_contact_company_contact_id");

                    b.HasOne("API.Models.Role", "Role")
                        .WithMany("CompanyContactRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_contact_role_roles_role_id");

                    b.Navigation("CompanyContact");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("API.Models.ContactEmail", b =>
                {
                    b.HasOne("API.Models.Contact", "Contact")
                        .WithMany("Emails")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_email_contact_contact_id");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("API.Models.EmailEvent", b =>
                {
                    b.HasOne("API.Models.EmailMessage", "EmailMessage")
                        .WithMany("Events")
                        .HasForeignKey("EmailMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_event_email_message_email_message_id");

                    b.Navigation("EmailMessage");
                });

            modelBuilder.Entity("API.Models.EmailLink", b =>
                {
                    b.HasOne("API.Models.EmailMessage", "EmailMessage")
                        .WithMany("Links")
                        .HasForeignKey("EmailMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_link_email_message_email_message_id");

                    b.Navigation("EmailMessage");
                });

            modelBuilder.Entity("API.Models.EmailMessage", b =>
                {
                    b.HasOne("API.Models.Campaign", "Campaign")
                        .WithMany("EmailMessages")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_email_message_campaigns_campaign_id");

                    b.HasOne("API.Models.CompanyContact", "CompanyContact")
                        .WithMany("EmailMessages")
                        .HasForeignKey("CompanyContactId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_email_message_company_contact_company_contact_id");

                    b.HasOne("API.Models.Contact", "Contact")
                        .WithMany("EmailMessages")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_email_message_contact_contact_id");

                    b.HasOne("API.Models.MailMergeTemplate", "MailMergeTemplate")
                        .WithMany("EmailMessages")
                        .HasForeignKey("MailMergeTemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_email_message_mail_merge_template_mail_merge_template_id");

                    b.Navigation("Campaign");

                    b.Navigation("CompanyContact");

                    b.Navigation("Contact");

                    b.Navigation("MailMergeTemplate");
                });

            modelBuilder.Entity("API.Models.ExternalRecordLink", b =>
                {
                    b.HasOne("API.Models.IntegrationConnection", "IntegrationConnection")
                        .WithMany("ExternalRecordLinks")
                        .HasForeignKey("IntegrationConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_record_link_integration_connection_integration_con");

                    b.Navigation("IntegrationConnection");
                });

            modelBuilder.Entity("API.Models.IntegrationSyncLog", b =>
                {
                    b.HasOne("API.Models.ExternalRecordLink", "ExternalRecordLink")
                        .WithMany("SyncLogs")
                        .HasForeignKey("ExternalRecordLinkId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_integration_sync_log_external_record_link_external_record_l");

                    b.HasOne("API.Models.IntegrationConnection", "IntegrationConnection")
                        .WithMany("SyncLogs")
                        .HasForeignKey("IntegrationConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integration_sync_log_integration_connection_integration_con");

                    b.Navigation("ExternalRecordLink");

                    b.Navigation("IntegrationConnection");
                });

            modelBuilder.Entity("API.Models.MailMergeTemplateField", b =>
                {
                    b.HasOne("API.Models.MergeField", "MergeField")
                        .WithMany("TemplateFields")
                        .HasForeignKey("MergeFieldKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mail_merge_template_field_merge_field_merge_field_key");

                    b.HasOne("API.Models.MailMergeTemplate", "Template")
                        .WithMany("TemplateFields")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mail_merge_template_field_mail_merge_template_template_id");

                    b.Navigation("MergeField");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("API.Models.Campaign", b =>
                {
                    b.Navigation("CampaignContacts");

                    b.Navigation("EmailMessages");
                });

            modelBuilder.Entity("API.Models.CampaignActivity", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("API.Models.CampaignContact", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("API.Models.Company", b =>
                {
                    b.Navigation("CompanyContacts");
                });

            modelBuilder.Entity("API.Models.CompanyContact", b =>
                {
                    b.Navigation("EmailMessages");

                    b.Navigation("Emails");

                    b.Navigation("Phones");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("API.Models.Contact", b =>
                {
                    b.Navigation("CompanyContacts");

                    b.Navigation("EmailMessages");

                    b.Navigation("Emails");
                });

            modelBuilder.Entity("API.Models.EmailMessage", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Links");
                });

            modelBuilder.Entity("API.Models.ExternalRecordLink", b =>
                {
                    b.Navigation("SyncLogs");
                });

            modelBuilder.Entity("API.Models.IntegrationConnection", b =>
                {
                    b.Navigation("ExternalRecordLinks");

                    b.Navigation("SyncLogs");
                });

            modelBuilder.Entity("API.Models.MailMergeTemplate", b =>
                {
                    b.Navigation("EmailMessages");

                    b.Navigation("TemplateFields");
                });

            modelBuilder.Entity("API.Models.MergeField", b =>
                {
                    b.Navigation("TemplateFields");
                });

            modelBuilder.Entity("API.Models.Role", b =>
                {
                    b.Navigation("CompanyContactRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
