// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407214246_add_external_integration")]
    partial class add_external_integration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("Address2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address2");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<bool>("Collections")
                        .HasColumnType("boolean")
                        .HasColumnName("collections");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<bool?>("CompanySpecialBilling")
                        .HasColumnType("boolean")
                        .HasColumnName("company_special_billing");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<long?>("HubspotCompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("hubspot_company_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsNewCompany")
                        .HasColumnType("boolean")
                        .HasColumnName("is_new_company");

                    b.Property<DateTimeOffset?>("LastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<string>("LegacyPrimaryCategory")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legacy_primary_category");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("PrimaryRepName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("primary_rep_name");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<string>("TaxId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tax_id");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.Property<bool>("WriteOff")
                        .HasColumnType("boolean")
                        .HasColumnName("write_off");

                    b.Property<string>("Zip")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("API.Models.CompanyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_company_contact");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_company_contact_company_id");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_company_contact_contact_id");

                    b.HasIndex("CompanyId", "ContactId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_contact_company_id_contact_id");

                    b.HasIndex("CompanyId", "IsPrimary")
                        .HasDatabaseName("ix_company_contact_company_id_is_primary");

                    b.ToTable("company_contact", (string)null);
                });

            modelBuilder.Entity("API.Models.CompanyContactEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_contact_id");

                    b.Property<bool>("DoNotEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("do_not_email");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.HasKey("Id")
                        .HasName("pk_company_contact_email");

                    b.HasIndex("CompanyContactId")
                        .HasDatabaseName("ix_company_contact_email_company_contact_id");

                    b.HasIndex("Email", "CompanyContactId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_contact_email_email_company_contact_id");

                    b.ToTable("company_contact_email", (string)null);
                });

            modelBuilder.Entity("API.Models.CompanyContactPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_contact_id");

                    b.Property<bool>("DoNotCall")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("do_not_call");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_company_contact_phone");

                    b.HasIndex("CompanyContactId")
                        .HasDatabaseName("ix_company_contact_phone_company_contact_id");

                    b.HasIndex("Phone", "CompanyContactId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_contact_phone_phone_company_contact_id");

                    b.ToTable("company_contact_phone", (string)null);
                });

            modelBuilder.Entity("API.Models.CompanyContactRole", b =>
                {
                    b.Property<Guid>("CompanyContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_contact_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("CompanyContactId", "RoleId")
                        .HasName("pk_company_contact_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_company_contact_role_role_id");

                    b.ToTable("company_contact_role", (string)null);
                });

            modelBuilder.Entity("API.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_date");

                    b.Property<string>("Department")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("department");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gender");

                    b.Property<string>("HubspotId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hubspot_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("job_title");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_updated_date");

                    b.Property<string>("LeadSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lead_source");

                    b.Property<string>("LeadStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lead_status");

                    b.Property<string>("Salutation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("salutation");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<string>("UserRepId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_rep_id");

                    b.Property<string>("Zip")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_contact");

                    b.HasIndex("FirstName")
                        .HasDatabaseName("ix_contact_first_name");

                    b.HasIndex("HubspotId")
                        .HasDatabaseName("ix_contact_hubspot_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_contact_is_active");

                    b.HasIndex("LastName")
                        .HasDatabaseName("ix_contact_last_name");

                    b.HasIndex("UserRepId")
                        .HasDatabaseName("ix_contact_user_rep_id");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("ix_contact_first_name_last_name");

                    b.HasIndex("LastName", "FirstName", "City")
                        .HasDatabaseName("ix_contact_last_name_first_name_city");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("API.Models.ContactEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<bool>("DoNotEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("do_not_email");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.HasKey("Id")
                        .HasName("pk_contact_email");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_contact_email_contact_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_contact_email_email");

                    b.ToTable("contact_email", (string)null);
                });

            modelBuilder.Entity("API.Models.ExternalIdMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("InternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("internal_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_table");

                    b.HasKey("Id")
                        .HasName("pk_external_id_map");

                    b.HasIndex("SourceSystem", "SourceTable", "SourceId", "EntityType")
                        .IsUnique()
                        .HasDatabaseName("ix_external_id_map_source_system_source_table_source_id_entity");

                    b.ToTable("external_id_map", (string)null);
                });

            modelBuilder.Entity("API.Models.ExternalRecordLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_entity_type");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<Guid>("IntegrationConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_connection_id");

                    b.Property<Guid>("InternalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("internal_entity_id");

                    b.Property<string>("InternalEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("internal_entity_type");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_sync_error");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("ProviderMetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("provider_metadata_json");

                    b.Property<string>("SyncStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sync_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_external_record_link");

                    b.HasIndex("IntegrationConnectionId", "ExternalEntityType", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_external_record_link_integration_connection_id_external_ent");

                    b.HasIndex("IntegrationConnectionId", "InternalEntityType", "InternalEntityId", "ExternalEntityType")
                        .IsUnique()
                        .HasDatabaseName("ix_external_record_link_integration_connection_id_internal_ent");

                    b.ToTable("external_record_link", (string)null);
                });

            modelBuilder.Entity("API.Models.IntegrationConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("auth_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_integration_connection");

                    b.HasIndex("Provider", "DisplayName")
                        .IsUnique()
                        .HasDatabaseName("ix_integration_connection_provider_display_name");

                    b.ToTable("integration_connection", (string)null);
                });

            modelBuilder.Entity("API.Models.IntegrationSyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("direction");

                    b.Property<Guid?>("ExternalRecordLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_record_link_id");

                    b.Property<Guid>("IntegrationConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_connection_id");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_integration_sync_log");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_integration_sync_log_created_at");

                    b.HasIndex("ExternalRecordLinkId")
                        .HasDatabaseName("ix_integration_sync_log_external_record_link_id");

                    b.HasIndex("IntegrationConnectionId")
                        .HasDatabaseName("ix_integration_sync_log_integration_connection_id");

                    b.ToTable("integration_sync_log", (string)null);
                });

            modelBuilder.Entity("API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_role_name");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsSystem = true,
                            Name = "Billing"
                        },
                        new
                        {
                            Id = 2,
                            IsSystem = true,
                            Name = "Print Artwork"
                        },
                        new
                        {
                            Id = 3,
                            IsSystem = true,
                            Name = "Digital Artwork"
                        },
                        new
                        {
                            Id = 4,
                            IsSystem = true,
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("API.Models.CompanyContact", b =>
                {
                    b.HasOne("API.Models.Company", "Company")
                        .WithMany("CompanyContacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_contact_company_company_id");

                    b.HasOne("API.Models.Contact", "Contact")
                        .WithMany("CompanyContacts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_contact_contact_contact_id");

                    b.Navigation("Company");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("API.Models.CompanyContactEmail", b =>
                {
                    b.HasOne("API.Models.CompanyContact", "CompanyContact")
                        .WithMany("Emails")
                        .HasForeignKey("CompanyContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_contact_email_company_contact_company_contact_id");

                    b.Navigation("CompanyContact");
                });

            modelBuilder.Entity("API.Models.CompanyContactPhone", b =>
                {
                    b.HasOne("API.Models.CompanyContact", "CompanyContact")
                        .WithMany("Phones")
                        .HasForeignKey("CompanyContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_contact_phone_company_contact_company_contact_id");

                    b.Navigation("CompanyContact");
                });

            modelBuilder.Entity("API.Models.CompanyContactRole", b =>
                {
                    b.HasOne("API.Models.CompanyContact", "CompanyContact")
                        .WithMany("Roles")
                        .HasForeignKey("CompanyContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_contact_role_company_contact_company_contact_id");

                    b.HasOne("API.Models.Role", "Role")
                        .WithMany("CompanyContactRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_contact_role_roles_role_id");

                    b.Navigation("CompanyContact");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("API.Models.ContactEmail", b =>
                {
                    b.HasOne("API.Models.Contact", "Contact")
                        .WithMany("Emails")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_email_contact_contact_id");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("API.Models.ExternalRecordLink", b =>
                {
                    b.HasOne("API.Models.IntegrationConnection", "IntegrationConnection")
                        .WithMany("ExternalRecordLinks")
                        .HasForeignKey("IntegrationConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_record_link_integration_connection_integration_con");

                    b.Navigation("IntegrationConnection");
                });

            modelBuilder.Entity("API.Models.IntegrationSyncLog", b =>
                {
                    b.HasOne("API.Models.ExternalRecordLink", "ExternalRecordLink")
                        .WithMany("SyncLogs")
                        .HasForeignKey("ExternalRecordLinkId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_integration_sync_log_external_record_link_external_record_l");

                    b.HasOne("API.Models.IntegrationConnection", "IntegrationConnection")
                        .WithMany("SyncLogs")
                        .HasForeignKey("IntegrationConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integration_sync_log_integration_connection_integration_con");

                    b.Navigation("ExternalRecordLink");

                    b.Navigation("IntegrationConnection");
                });

            modelBuilder.Entity("API.Models.Company", b =>
                {
                    b.Navigation("CompanyContacts");
                });

            modelBuilder.Entity("API.Models.CompanyContact", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Phones");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("API.Models.Contact", b =>
                {
                    b.Navigation("CompanyContacts");

                    b.Navigation("Emails");
                });

            modelBuilder.Entity("API.Models.ExternalRecordLink", b =>
                {
                    b.Navigation("SyncLogs");
                });

            modelBuilder.Entity("API.Models.IntegrationConnection", b =>
                {
                    b.Navigation("ExternalRecordLinks");

                    b.Navigation("SyncLogs");
                });

            modelBuilder.Entity("API.Models.Role", b =>
                {
                    b.Navigation("CompanyContactRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
