-- 1. Create table if it doesn't exist
CREATE TABLE IF NOT EXISTS staging.dim_company_prepped
(
    company_id                 integer,
    legacy_sid                 integer,
    root_company_id            integer,
    channel_id                 integer,
    instance_key               text,
    company_name               text,
    address                    text,
    address2                   text,
    city                       text,
    state                      text,
    zip                        text,
    country                    text,
    website_url                text,
    category                   text,
    company_type               text,
    primary_category           text,
    primary_rep_name           text,
    currency_id                integer,
    tax_id                     text,
    company_xref               text,
    hubspot_company_id         bigint,
    billing_contact_id         integer,
    primary_contact_id         integer,
    print_artwork_contact_id   integer,
    digital_artwork_contact_id integer,
    latitude                   numeric(9, 6),
    longitude                  numeric(9, 6),
    created_date               timestamp,
    last_update                timestamp,
    instance_live_date         timestamp,
    instance_link              text,
    instance_users             integer,
    collections                boolean,
    write_off                  boolean,
    dead                       boolean,
    is_new_company             boolean,
    company_special_billing    boolean,

    CONSTRAINT dim_company_prepped_company_id_key UNIQUE (company_id)
);

ALTER TABLE staging.dim_company_prepped
    OWNER TO postgres;


-- 2. Insert data, casting types + ignoring duplicates
INSERT INTO staging.dim_company_prepped (
    company_id,
    root_company_id,
    channel_id,
    instance_key,
    company_name,
    address,
    address2,
    city,
    state,
    zip,
    country,
    website_url,
    category,
    company_type,
    primary_category,
    primary_rep_name,
    currency_id,
    tax_id,
    company_xref,
    hubspot_company_id,
    billing_contact_id,
    primary_contact_id,
    print_artwork_contact_id,
    digital_artwork_contact_id,
    latitude,
    longitude,
    created_date,
    last_update,
    instance_live_date,
    instance_link,
    instance_users,
    collections,
    write_off,
    dead,
    is_new_company,
    company_special_billing
)
SELECT
    company_id::integer,
    root_company_id::integer,
    channel_id::integer,
    instance_key,
    company_name,
    address,
    address2,
    city,
    state,
    zip,
    country,
    website_url,
    category,
    type,
    primary_category,
    primary_rep_name,
    currency_id::integer,
    tax_id,
    company_xref,
    hubspot_company_id::bigint,
    billing_contact_id::integer,
    primary_contact_id::integer,
    print_artwork_contact_id::integer,
    digital_artwork_contact_id::integer,
    NULLIF(latitude, '')::numeric,
    NULLIF(longitude, '')::numeric,
    NULLIF(created_date, '')::timestamp,
    NULLIF(lastupdate, '')::timestamp,
    NULLIF(instance_live_date, '')::timestamp,
    instance_link,
    instance_users::integer,
    collections::boolean,
    write_off::boolean,
    dead::boolean,
    is_new_company::boolean,
    company_special_billing::boolean
FROM staging.dim_company
ON CONFLICT (company_id) DO NOTHING;