-- 1. Create table if it doesn't exist
CREATE TABLE IF NOT EXISTS staging.dim_contact_prepped
(
    s_id               varchar(256),
    channel_id         varchar(256),
    instance_key       varchar(256),
    company_name       varchar(256),
    first_name         varchar(256),
    last_name          varchar(256),
    address_line_1     varchar(256),
    address_line_2     varchar(256),
    city               varchar(256),
    state              varchar(256),
    zip                varchar(256),
    country            varchar(256),
    salutation         varchar(256),
    email              varchar(256),
    phone              varchar(256),
    contact_id         integer PRIMARY KEY,
    company_id         integer,
    owned_by_rep_id    varchar(256),
    is_dead            boolean,
    gender             varchar(256),
    lead_source        varchar(256),
    lead_status        varchar(256),
    contact_type       varchar(256),
    contact_xref       varchar(256),
    hubspot_contact_id varchar(256),
    job_title          varchar(256),
    department         varchar(256),
    latitude           numeric(10, 7),
    longitude          numeric(10, 7),
    created_date       timestamp,
    instance_link      text,
    last_update        timestamp
    );

ALTER TABLE staging.dim_contact_prepped
    OWNER TO postgres;


-- 2. Insert from source (assuming source is staging.dim_contact)
INSERT INTO staging.dim_contact_prepped (
    s_id,
    channel_id,
    instance_key,
    company_name,
    first_name,
    last_name,
    address_line_1,
    address_line_2,
    city,
    state,
    zip,
    country,
    salutation,
    email,
    phone,
    contact_id,
    company_id,
    owned_by_rep_id,
    is_dead,
    gender,
    lead_source,
    lead_status,
    contact_type,
    contact_xref,
    hubspot_contact_id,
    job_title,
    department,
    latitude,
    longitude,
    created_date,
    instance_link,
    last_update
)
SELECT
    s_id,
    channel_id,
    instance_key,
    company_name,
    first_name,
    last_name,
    address_line_1,
    address_line_2,
    city,
    state,
    zip,
    country,
    salutation,
    email,
    phone,
    contact_id::integer,
    company_id::integer,
    owned_by_rep_id,
    is_dead::boolean,
    gender,
    lead_source,
    lead_status,
    contact_type,
    contact_xref,
    hubspot_contact_id,
    job_title,
    department,
    NULLIF(latitude, '')::numeric,
    NULLIF(longitude, '')::numeric,
    NULLIF(created_date, '')::timestamp,
    instance_link,
    NULLIF(last_update, '')::timestamp
FROM staging.dim_contact
    ON CONFLICT (contact_id) DO NOTHING;