@hostname=localhost
@port=7227
@authPort=7032
@baseUrl=https://{{hostname}}:{{port}}/api

### Get Access Token
POST https://{{hostname}}:{{authPort}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&
username=joe@egmrc.com&
password={{devPassword}}&
client_id=next-app&
client_secret={{clientSecret}}&
scope=api openid profile

> {%
    client.global.set("auth_token", response.body.access_token);
%}

### Get all campaigns
GET {{baseUrl}}/Campaigns
Accept: application/json
Authorization: Bearer {{auth_token}}

### Create a new campaign
POST {{baseUrl}}/Campaigns
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Spring Sale 2026",
  "description": "Promotion for the spring collection",
  "status": "Draft"
}

### Get campaign by ID
# Replace {id} with a valid campaign GUID
@campaignId = a7383872-91f6-41f8-8440-cbb9ab1775cc
GET {{baseUrl}}/Campaigns/{{campaignId}}
Accept: application/json
Authorization: Bearer {{auth_token}}

### Add contacts to campaign
POST {{baseUrl}}/Campaigns/{{campaignId}}/contacts
Content-Type: application/json
Authorization: Bearer {{auth_token}}
*
[
  "9eb6aeb8-42cc-4a01-a365-26a011053c29",
  "b712fadc-b909-4672-82e9-1fe879be0bea"
]

### Add contacts to campaign by companies (all company contacts)
POST {{baseUrl}}/Campaigns/{{campaignId}}/companies
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "companyIds": [
    "11111111-1111-1111-1111-111111111111",
    "22222222-2222-2222-2222-222222222222"
  ],
  "primaryContactsOnly": false,
  "companyContactRoleIds": []
}

### Add contacts to campaign by companies (primary contacts only)
POST {{baseUrl}}/Campaigns/{{campaignId}}/companies
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "companyIds": [
    "496e97ed-9996-4f1c-8bd5-99a261ef45a9"
  ],
  "primaryContactsOnly": true,
  "companyContactRoleIds": []
}

### Add contacts to campaign by companies (filter by company contact role ids)
POST {{baseUrl}}/Campaigns/{{campaignId}}/companies
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "companyIds": [
    "11111111-1111-1111-1111-111111111111"
  ],
  "primaryContactsOnly": false,
  "companyContactRoleIds": [1, 3]
}
