@hostname=localhost
@port=7227
@authPort=7032
@baseUrl=https://{{hostname}}:{{port}}/api/v1

### Get Access Token
POST https://{{hostname}}:{{authPort}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&
username=joe@egmrc.com&
password={{devPassword}}&
client_id=next-app&
client_secret={{clientSecret}}&
scope=api openid profile

> {%
    client.global.set("auth_token", response.body.access_token);
%}

### Send email
POST {{baseUrl}}/EmailMarketing/send
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "toEmail": "joe@egmrc.com",
  "subject": "Test send",
  "htmlBody": "<p>Hello from Ad Platform</p>"
}

### Schedule email
POST {{baseUrl}}/EmailMarketing/schedule
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "toEmail": "test@egmrc.com",
  "toName": "Joe",
  "subject": "Scheduled test send",
  "htmlBody": "<p>Hello later from Ad Platform</p>",
  "plainTextBody": "Hello later from Ad Platform",
  "scheduledFor": "2026-05-16T15:00:00Z"
}

> {%
    client.global.set("email_message_id", response.body.emailMessageId);
%}

### Reschedule email
POST {{baseUrl}}/EmailMarketing/{{email_message_id}}/reschedule
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "scheduledFor": "2026-05-16T16:00:00Z"
}

### Cancel scheduled email
POST {{baseUrl}}/EmailMarketing/{{email_message_id}}/cancel
Authorization: Bearer {{auth_token}}
